name: Rainbow Music Led OS release

on:
  repository_dispatch:
    types: [hyperion_push]

jobs:
  rpi-image:
    name: "Build Rainbow Music Led OS image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils quilt parted qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc

      # build image
      - name: Build Rainbow Music Led OS
        run: |
          git clone https://github.com/tihoangyeudau/Hyperbian-1.git
          git clone https://github.com/tihoangyeudau/pi-gen.git
          touch ./pi-gen/stage3/SKIP ./pi-gen/stage4/SKIP ./pi-gen/stage4/SKIP_IMAGES
          touch ./pi-gen/stage5/SKIP ./pi-gen/stage5/SKIP_IMAGES
          cp -R ./Hyperbian-1/stage-hyperbian ./pi-gen/stage-hyperbian
          cp ./Hyperbian-1/config ./pi-gen/config && cd pi-gen
          sudo ./build.sh
          sudo mv ./deploy/*.zip ./deploy/Hyperbian.zip
          sudo chown -fR $(stat -c "%U:%G" .) ./deploy

      - name: Delete previous Rainbow Music Led OS Release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # create release and upload image
      - name: Create release and upload image
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pi-gen/deploy/Hyperbian.zip
          asset_name: Hyperbian.zip
          tag: Hyperbian
          release_name: Hyperbian
          body: "Raspberry Pi OS Lite with [Ambilight WiFi](https://rainbowmusicled.com) pre installed. Also called Rainbow Music Led OS."
          overwrite: true
